version: '2.4'
services:
  postgre-prod:
    image: postgres:14
    container_name: postgre-prod
    environment:
      POSTGRES_PASSWORD: 1212
      POSTGRES_USER: root
      POSTGRES_DB: ecommjava
      POSTGRES_INITDB_ARGS: "--nosync"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scriptdb.sql:/docker-entrypoint-initdb.d/scriptdb.sql
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ecommjava || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  ecomapp-prod:
    image: ecomapp-prod:latest
    container_name: ecomapp-prod
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgre-prod:5432/ecommjava
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1212
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8083:8083"
    depends_on:
      postgre-prod:
        condition: service_healthy
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge

volumes:
  postgres_data:
